import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Roboto } from "next/font/google";

// Fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const getRobot = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "700"],
  variable: "--font-roboto",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout Component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`roboto m-0 p-0 bg-[url('https://www.gran-turismo.com/images/c/i1thu8zNgZ9sjO.jpg')] bg-cover bg-center bg-fixed h-screen w-full overflow-x-hidden ${getRobot.variable} ${geistSans.variable} ${geistMono.variable} text-white`}
      >
        <>
        
        {children}
        </>
      </body>
    </html>
  );
}
